language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn prebuild

deploy:
  provider: surge
  skip_cleanup: true
  domain: special-chalk.surge.sh
  project: ./dist/

on:
  branch: master
